### ISSUE TITLE
Additional input (files, Internet) instead of hard-coded values for films

### ISSUE THREAD

**Issue by Vasar007** [Vasar007/ThingAppraiser#2]
**Is your feature request related to a problem? Please describe.**
We need to add support of input files and some other options.

**Describe the solution you'd like**
Implement work with files and services (e.g. Google Docs/Tables).

**Describe alternatives you've considered**
None.

**Additional context**
Files support is required, others are optional.

**Comment by danila19991** [comment]
@Vasar007 Which file formats we want to support?

**Comment by Vasar007** [comment]
@danila19991, you can choose yourself. Btw, think about encodings and portability.
